name: Build and upload release binaries

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build-binaries:
    name: Build release binaries
    permissions:
      contents: write
    strategy:
      matrix:
        arch:
          - x86_64
          - aarch64
          - arm
          - armv7
        os:
          - unknown-linux-musl
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: build
          target: ${{ matrix.arch }}-${{ matrix.os }}${{ contains(matrix.arch, 'arm') && 'eabi' || '' }}
          args: "--release --locked --features all"
      - name: Create archive
        env:
          BIN_NAME: "skim-run"
          ARCH: "${{ matrix.arch }}-${{ matrix.os }}${{ contains(matrix.arch, 'arm') && 'eabi' || '' }}"
        run: |
          ls -R
          cp "target/$ARCH/release/$BIN_NAME" "$BIN_NAME-$ARCH"
      - name: Upload binary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BIN: "skim-run-${{ matrix.arch }}-${{ matrix.os }}${{ contains(matrix.arch, 'arm') && 'eabi' || '' }}"
          TAG: ${{ github.ref_name }}
        run: |
          gh release upload "$TAG" "$RELEASE_BIN"
